### ISSUE TITLE
Design and update landing page

### ISSUE THREAD

**Issue by ajose01** [code-newbies/ruby-monday-blog#10]
so that a new user will have a welcome and overview of what our app will do.

Tied to issue #4 and #8

**Comment by jaywilburn** [comment]
I can take this.

**Comment by jaywilburn** [comment]
I've added a landing page design with dummy data and images.

**Comment by matugm** [comment]
I think it is useful to leave a link to the relevant commit: https://github.com/code-newbies/ruby-monday-blog/commit/983e33c7788b9126af06fd8916cbc4e9685f8a0f

**Comment by ajose01** [comment]
Boom. Closed issue. Thanks.
