### ISSUE TITLE
As collaborators we want to test our code

### ISSUE THREAD

**Issue by ajose01** [code-newbies/ruby-monday-blog#11]
and follow TDD. Set up rspec gem so that we can include this in our process.

**Comment by trisalar** [comment]
Oops, sorry guys, I'm still new at this and didn't know we had to be assigned to tasks before working on it and sending pull requests. I have sent a pull request for this one, so I'll self assign this one.

**Comment by claytonflesher** [comment]
I merged the pull request. Closing out this issue. Thanks CynrickChiu.
