### ISSUE TITLE
As users we want to be able to add tags to posts.

### ISSUE THREAD

**Issue by ajose01** [code-newbies/ruby-monday-blog#13]
Rather than using a hierarchal system, we will be using 'tags' to organize and classify our posts.

Look for 'tagging' / 'tags' solutions, discuss and propose in slack channel and set-up.

Tied to #6

**Comment by farishkash** [comment]
Ok will start working on this.

**Comment by ajose01** [comment]
Will create a new ticket for 'filtering'. Pull posts with specific tags. Does not include searching blog text.

**Comment by farishkash** [comment]
Closing this as I completed this on Tuesday.
