### ISSUE TITLE
Come up with a seed db to have initial content.

### ISSUE THREAD

**Issue by ajose01** [code-newbies/ruby-monday-blog#25]
Need to have dummy data so that we can have an idea of layouts, context for dev environments.

Possibly use a seeding gem (faker) to help those working on project.

**Comment by matugm** [comment]
Here is an example of using faker to generate data:

```
require 'faker'

20.times do
  post = Post.create!(title: Faker::Lorem.word, body: Faker::Lorem.paragraph)
  puts "Created #{post.title}"
end
```

**Comment by ajose01** [comment]
Closed.
