### ISSUE TITLE
Clean-up branches

### ISSUE THREAD

**Issue by matugm** [code-newbies/ruby-monday-blog#29]
I think we should start deleting branches that we don't need anymore (I believe that should be most of them).

**Comment by jaywilburn** [comment]
We have to clean this up, any takers?

**Comment by matugm** [comment]
Done, to keep our branches clean we should probably delete them after merging.

![image](https://cloud.githubusercontent.com/assets/1369748/9061618/4cf06600-3abd-11e5-8876-296070f6236f.png)

Here is image of what it looks like.
