### ISSUE TITLE
User authentication

### ISSUE THREAD

**Issue by ajose01** [code-newbies/ruby-monday-blog#3]
As the owners of this app, we want to add user authentication so only authorized users can access secured areas of the app. Set up devise to deal with authentication.

https://github.com/plataformatec/devise

**Comment by KaraAJC** [comment]
I'd love to work on this with someone, if they want to pair! (I have experience with this, so if someone wants to learn we can do it together)

**Comment by nicolaguidi** [comment]
I'm a bit lost, I'd like someone with a bit of experience in team working.

**Comment by KaraAJC** [comment]
@nicolaguidi would you like to set up a time to work together on this task? I'm available after 1PM CST. 

Kara C

**Comment by claytonflesher** [comment]
I assigned it myself. If someone hasn't submitted a pull request by Wednesday, I'll do it.

**Comment by claytonflesher** [comment]
Closing issue.

**Comment by ajose01** [comment]
Nice! We have a user_controller and user model, with authentication. Thanks
