### ISSUE TITLE
Make devise views use bootstrap

### ISSUE THREAD

**Issue by matugm** [code-newbies/ruby-monday-blog#32]
The default devise views are pretty ugly.

We can use `rails generate devise:views -v passwords registrations session` to get a copy of the view code into the project. Then we can use the [rails-bootstrap-forms](https://github.com/bootstrap-ruby/rails-bootstrap-forms) gem to style them.

I used to convert my forms to bootstrap by hand, which is a lot of work. But this gem does the hard work for you :)

This is what a form with `rails-bootstrap-forms` looks like (without any extra styling):

![image](https://cloud.githubusercontent.com/assets/1369748/8762845/a4aa8542-2d84-11e5-92d4-01485168d57c.png)

And with a few more tweaks:

![image](https://cloud.githubusercontent.com/assets/1369748/8762881/e5ab6056-2d85-11e5-9c09-7b0fce445f37.png)

**Comment by matugm** [comment]
Already did this for the post form in this PR: https://github.com/code-newbies/ruby-monday-blog/pull/33

What remains now is to extend this work to the rest of the application.

**Comment by jaywilburn** [comment]
FYI, these will be designed to match the app as myself and Mary are working on the UI side of things.

**Comment by jaywilburn** [comment]
Mary and Jesus resolved this.
