### ISSUE TITLE
As visitors to our site, we want to see a landing page

### ISSUE THREAD

**Issue by ajose01** [code-newbies/ruby-monday-blog#4]
A landing page will provide users with a welcome message / info to our app.

This will require setting up a static_pages controller along with an index page. Edit routes.rb to make this index page the root page.

Design of index page will be a separate ticket. For now leave with a < h1 > header with copy:
"Welcome to the Ruby-Monday blog!"

**Comment by brascoder** [comment]
I'll take this one

**Comment by jaywilburn** [comment]
Added the landing page - please review. 
Right now it's just dummy data.
