### ISSUE TITLE
Wireframing of blog app

### ISSUE THREAD

**Issue by ajose01** [code-newbies/ruby-monday-blog#5]
As we contributors and developers of this app, we will need reference points to ensure we are building according to our group ideas.

Put together some basic wireframing that will be added to the Readme/Wiki of the app.

**Comment by jaywilburn** [comment]
I can do this first, this will help us get a visual of everything we need in the app.

**Comment by mkmckenzie** [comment]
Created wireframes: 
Create (would be the same for "edit") post: https://wireframe.cc/dHmgGg
View all posts (supposed to correspond to "show" view, but that only contains one post at the moment): https://wireframe.cc/Uo6prn

Finished implementing on Create Post page, working on view all posts (.../posts/) now.

**Comment by mkmckenzie** [comment]
Finished wireframing the views that were populated, need to discuss what features are going to be implemented (edit/destroy posts/tags; comments? disqus or form?) so I can put together a wireframe for that too. Color, typography will need to be added later.

**Comment by ajose01** [comment]
Awesome job @mkmckenzie
