### ISSUE TITLE
Refactor views

### ISSUE THREAD

**Issue by matugm** [code-newbies/ruby-monday-blog#52]
Things that need to be done:
- Fix indentation to be consistent across the board
- Extract partials

**Comment by allanbreyes** [comment]
I can knock out the indentation real quick after next Monday.  Definitely recommend we do this AFTER a bunch of merged PRs, otherwise it will be git merge conflicts up the wazoo.  Also, I think we should set up a common standard (e.g. spaces instead of tabs, 2-space indents, etc.)

**Comment by claytonflesher** [comment]
Yes please on the spaces instead of tabs. That's killing us.

People should be setting up their text editors to default to spaces. Be sure and mention it in the discussion next week.

**Comment by allanbreyes** [comment]
Pretty sure [tidy-html5](http://www.htacg.org/tidy-html5/documentation/) can do this wholesale and recursively for html files... not sure if it will butcher up .erb files though.

_edit_: nvm, this is probably the way to go - https://github.com/threedaymonk/htmlbeautifier
