### ISSUE TITLE
Duplicate post tags should be invalidated in PostTag model + database

### ISSUE THREAD

**Issue by allanbreyes** [code-newbies/ruby-monday-blog#57]
![image](https://cloud.githubusercontent.com/assets/7947900/9204455/fdf19d06-4022-11e5-845c-0fae809d3e58.png)

As shown, the 'Angular' tag is allowed to be added multiple times.  Scoped uniqueness should be enforced at the model and database layer, rather than the views or controllers.

**Comment by ghost** [comment]
is this a problem with database information, or mvc app code?  Maybe resetting the database might clean this up, but I'm pretty sure that's a aggressive move.

**Comment by matugm** [comment]
Do you have the latest version? This should be already fixed by my PR #51 that we merged yesterday.

**Comment by allanbreyes** [comment]
I _think_ I have the latest?  I think #51 enforces uniqueness on tag content, but this issue and PR #58 enforces uniqueness on `post_tag`.  Basically, you can't add multiple 'Angular' tags to the same post (see screenshot).

**Comment by matugm** [comment]
I see. I don't think we support multiple tags yet. When I try to reproduce the problem via the 'new post' form I get this:

![image](https://cloud.githubusercontent.com/assets/1369748/9209326/21b8bf1e-4076-11e5-8a62-afe6d3836ec5.png)

I also tried separating by commas, we probably need one field per tag or to pre-process the field. How are you adding the multiple tags?

**Comment by allanbreyes** [comment]
Yea, just confirmed it.  (Spec does, too).  Just pulled from upstream#master, and here's what _shouldn't_ be allowed by the database or application.

```
irb(main):001:0> Post.first.tags
  Post Load (0.3ms)  SELECT  "posts".* FROM "posts"  ORDER BY "posts"."id" ASC LIMIT 1
  Tag Load (0.3ms)  SELECT "tags".* FROM "tags" INNER JOIN "post_tags" ON "tags"."id" = "post_tags"."tag_id" WHERE "post_tags"."post_id" = $1  [["post_id", 1]]
=> #<ActiveRecord::Associations::CollectionProxy []>
irb(main):002:0> Post.first.tags << Tag.first
  Post Load (0.7ms)  SELECT  "posts".* FROM "posts"  ORDER BY "posts"."id" ASC LIMIT 1
  Tag Load (0.4ms)  SELECT  "tags".* FROM "tags"  ORDER BY "tags"."id" ASC LIMIT 1
   (0.1ms)  BEGIN
  SQL (0.1ms)  INSERT INTO "post_tags" ("post_id", "tag_id") VALUES ($1, $2)  [["post_id", 1], ["tag_id", 1]]
   (4.0ms)  COMMIT
  Tag Load (0.3ms)  SELECT "tags".* FROM "tags" INNER JOIN "post_tags" ON "tags"."id" = "post_tags"."tag_id" WHERE "post_tags"."post_id" = $1  [["post_id", 1]]
=> #<ActiveRecord::Associations::CollectionProxy [#<Tag id: 1, created_at: "2015-08-11 20:11:51", updated_at: "2015-08-11 20:11:51", content: "Ruby on Rails">]>
irb(main):003:0> Post.first.tags << Tag.first
  Post Load (0.3ms)  SELECT  "posts".* FROM "posts"  ORDER BY "posts"."id" ASC LIMIT 1
  Tag Load (0.2ms)  SELECT  "tags".* FROM "tags"  ORDER BY "tags"."id" ASC LIMIT 1
   (0.1ms)  BEGIN
  SQL (0.1ms)  INSERT INTO "post_tags" ("post_id", "tag_id") VALUES ($1, $2)  [["post_id", 1], ["tag_id", 1]]
   (4.0ms)  COMMIT
  Tag Load (0.2ms)  SELECT "tags".* FROM "tags" INNER JOIN "post_tags" ON "tags"."id" = "post_tags"."tag_id" WHERE "post_tags"."post_id" = $1  [["post_id", 1]]
=> #<ActiveRecord::Associations::CollectionProxy [#<Tag id: 1, created_at: "2015-08-11 20:11:51", updated_at: "2015-08-11 20:11:51", content: "Ruby on Rails">, #<Tag id: 1, created_at: "2015-08-11 20:11:51", updated_at: "2015-08-11 20:11:51", content: "Ruby on Rails">]>
irb(main):004:0> Post.first.tags << Tag.first
  Post Load (0.6ms)  SELECT  "posts".* FROM "posts"  ORDER BY "posts"."id" ASC LIMIT 1
  Tag Load (0.4ms)  SELECT  "tags".* FROM "tags"  ORDER BY "tags"."id" ASC LIMIT 1
   (0.1ms)  BEGIN
  SQL (0.1ms)  INSERT INTO "post_tags" ("post_id", "tag_id") VALUES ($1, $2)  [["post_id", 1], ["tag_id", 1]]
   (4.1ms)  COMMIT
  Tag Load (0.3ms)  SELECT "tags".* FROM "tags" INNER JOIN "post_tags" ON "tags"."id" = "post_tags"."tag_id" WHERE "post_tags"."post_id" = $1  [["post_id", 1]]
=> #<ActiveRecord::Associations::CollectionProxy [#<Tag id: 1, created_at: "2015-08-11 20:11:51", updated_at: "2015-08-11 20:11:51", content: "Ruby on Rails">, #<Tag id: 1, created_at: "2015-08-11 20:11:51", updated_at: "2015-08-11 20:11:51", content: "Ruby on Rails">, #<Tag id: 1, created_at: "2015-08-11 20:11:51", updated_at: "2015-08-11 20:11:51", content: "Ruby on Rails">]>
irb(main):005:0> Post.first.tags
  Post Load (0.7ms)  SELECT  "posts".* FROM "posts"  ORDER BY "posts"."id" ASC LIMIT 1
  Tag Load (0.7ms)  SELECT "tags".* FROM "tags" INNER JOIN "post_tags" ON "tags"."id" = "post_tags"."tag_id" WHERE "post_tags"."post_id" = $1  [["post_id", 1]]
=> #<ActiveRecord::Associations::CollectionProxy [#<Tag id: 1, created_at: "2015-08-11 20:11:51", updated_at: "2015-08-11 20:11:51", content: "Ruby on Rails">, #<Tag id: 1, created_at: "2015-08-11 20:11:51", updated_at: "2015-08-11 20:11:51", content: "Ruby on Rails">, #<Tag id: 1, created_at: "2015-08-11 20:11:51", updated_at: "2015-08-11 20:11:51", content: "Ruby on Rails">]>
irb(main):006:0> 
```

Note: `Post.first` has **3** tags, all 'Ruby on Rails', id: 1

**Comment by matugm** [comment]
Right, so you are doing this via the rails console. I would say this is not really a bug (since a user can't possibly run into this), but a missing feature (multiple-tag support). Do you agree?

**Comment by allanbreyes** [comment]
I dunno, it's a model/database concern, and I think it should be validated at that level.  Front-end validation is brittle at best, and can be easily bypassed by using a JSON client (i.e. a POST via `curl`).

I'd personally want this validation at the model/database level, so that when we DO implement multiple-tag support on the front-end, it will prevent bad data from being written into the database.

**Comment by claytonflesher** [comment]
I added a need for multiple tags issue.

**Comment by matugm** [comment]
I understand that front-end 'validation' can be bypassed. But it's not a security issue.

I tend to not do things in avance so I would have expected this code to be part of a PR implementing multiple-tags. But I think it's fine after all, smaller PR's never hurt.
