### ISSUE TITLE
Need ability to store Posts into database

### ISSUE THREAD

**Issue by ajose01** [code-newbies/ruby-monday-blog#6]
In order to store posts into the database, we need to crate a Post model.

Create a post model and set corresponding associations.

**Comment by farishkash** [comment]
I like to take this one

**Comment by ajose01** [comment]
thanks @farishkash let us know how you're doing.

**Comment by farishkash** [comment]
Update, I already sent what I had done as a pull request.

Right now there is no post pages

I have a post model with
title: String
body: Text

Author should come from the first and last name of the user

Tags should be in it’s own controller so if changes are made to tagging system it is less likely to break posts

Should I push what I have at the moment and start working on a posts controller plus static pages?

**Comment by farishkash** [comment]
Close as it has been completed.
