### ISSUE TITLE
API keys and environmental variables management

### ISSUE THREAD

**Issue by allanbreyes** [code-newbies/ruby-monday-blog#61]
From side convo in #55

Will use Foreman, unless anyone has an issue with it.  Maybe we can share the dotenv files in the Slack chat.

**Comment by allanbreyes** [comment]
Need to know if we're using Heroku for deployment and/or what server (e.g. Puma, Unicorn) for Procfile setup.  Otherwise, maybe something like figaro would be of better use.

**Comment by matugm** [comment]
How about using Rails built-in `secrets.yml`? And btw we are using Heroku.

**Comment by allanbreyes** [comment]
We shouldn't commit any keys to the repository (secrets.yml is checked in by default), and having to do git --assume-unchanged or whatever gets a bit hairy!  Much easier to pass around a git-ignored dotenv or production.yml in the Slack channel.
