### ISSUE TITLE
Should tag#show post previews show the currently scoped tag? (or any tags at all?)

### ISSUE THREAD

**Issue by allanbreyes** [code-newbies/ruby-monday-blog#64]
References #56 implementation

Context: when navigating to the Angular tab#show page:
## Should the Angular tag be present?

![image](https://cloud.githubusercontent.com/assets/7947900/9216321/c53888ee-407c-11e5-8c99-2bc41a41530e.png)
## Hidden?

![image](https://cloud.githubusercontent.com/assets/7947900/9216313/a15840b8-407c-11e5-8a86-c8b4074cbd8e.png)
## Or, no tags displayed at all?

![image](https://cloud.githubusercontent.com/assets/7947900/9216335/f22eff7c-407c-11e5-99d3-8659477b8684.png)

**Comment by matugm** [comment]
Good question :) I think the 'hidden' one creates a bit of a weird situation: 'do all these post really have the tag I clicked on?'. I know it might sound a bit contrived but there are ppl like that: [Cognitive Dissonance](https://en.wikipedia.org/wiki/Cognitive_dissonance). Just my opinion.

**Comment by creativisionist** [comment]
^ +1

Having the tags present, albeit "technically" on all of them if navigated to said respective section, additionally makes it easier on and clearer for the user, i.e.: one less thing to think about/remember.  If tags are hidden then it makes sense to just use a filter but it would defeat the purpose of the tags, which is to immediately have available what relevant categories the post might belong to as well, despite whether a general filter may be present.

**Comment by allanbreyes** [comment]
I always err on the side of simplifying UI and reducing redundant data.  To me, having an Angular tab show in the "Posts tagged with Angular" is functionally no different than having a table:

### Cities in the State of California

| State | City | Pop. |
| --- | --- | --- |
| California | San Fransisco | 123,456 |
| California | San Jose | 123,456 |
| California | Sacramento | 123,456 |

If we're concerned about the user losing touch with the fact that he or she is in the "Posts tagged with Angular" section, then I think that's a UI problem--we just need to make the "[tag] Angular" title sticky and scroll with the user.

**Comment by creativisionist** [comment]
^ I agree that cleaner UI is nicer (personally-speaking, but this could also be contingent upon respective project at-hand).  I think a sticky scroll tag would have to be done carefully but it just depends how everything will look in conjunction with function/features.  Has there been any wireframing done post-whiteboarding?  That might help with determinants for initial sprint.

**Comment by allanbreyes** [comment]
Well... if the point of the project is to learn and practice Rails (as opposed to UI/UX), then I think the partial-filtering (hide Angular tags, but show all others) is techn(olog)ically more challenging!  At the end of the day, I'm happy with any of the three solutions, but I do find this one a whole lot more interesting to implement.

**Comment by matugm** [comment]
Just an example of a real-world implementation:

The CodeNewbie site has a tag system for the 'learn' section. It keeps showing all the tags (instead of filtering the current one).

http://www.codenewbie.org/learn/tags/workshops

**Comment by matugm** [comment]
We decided as a group to show all tags.
