### ISSUE TITLE
Add post author's name to blog post

### ISSUE THREAD

**Issue by jaywilburn** [code-newbies/ruby-monday-blog#69]
Add first & last name to blog post. "Written by first_name last_name"

**Comment by abinoam** [comment]
Can I take this?

**Comment by allanbreyes** [comment]
For sure! I think you'll need to add `first_name` / `last_name` to either `User` model or another model, like you mentioned in the Hangout.  I think @creativisionist is going to be working on that--great opportunity to work together!

**Comment by creativisionist** [comment]
@abinoam I'm adding custom fields to the devise gem (previous issue)

**Comment by abinoam** [comment]
Ok

**Comment by abinoam** [comment]
Where do you "save" what user did what post?

I mean, there's no `belongs_to :user` on Post model.

**Comment by allanbreyes** [comment]
Post doesn't have a user reference in the schema, so needs a migration also.

Can we add the `annotate` gem?  This would help tremendously.

**Comment by creativisionist** [comment]
FYI -- I pushed the changes to that specific branch so feel free to make changes and stuff!  Although -- for some reason the bootstrap customization wasn't working.  Branch is "add-custom-fields" but probably should be separate pull request for updating the posts.

**Comment by abinoam** [comment]
Hi @allanbreyes, I like annotate gem also!
