### ISSUE TITLE
Add ability to upload pictures to our app

### ISSUE THREAD

**Issue by ajose01** [code-newbies/ruby-monday-blog#7]
so that a user can include images in their blog post.

Initial set up of an image uploading gem that will handle this for our app.

See following link for some suggestions:
https://www.ruby-toolbox.com/categories/rails_file_uploads
Also discuss and ask for recommendations in slack channel. Once a gem is chosen, set it up and in comments explain to the team why that gem was chosen.

**Comment by pollygee** [comment]
I will give this a go, and I will probably ask for assistance in the slack channel as well as I haven't done this before!

**Comment by ajose01** [comment]
hi @pollygee how are you doing with this ticket? Do you need any help :)

**Comment by farishkash** [comment]
Message sent to pollygee in Slack, I will like to take this over.

**Comment by farishkash** [comment]
Ok just need to discuss sizes or any additional features on Monday's meeting otherwise this is done.

**Comment by matugm** [comment]
I think we can close this :) https://github.com/code-newbies/ruby-monday-blog/commit/47d24201e8d3097a73fc05e70e78aff3183c774e
