### ISSUE TITLE
Delete all old and merged branches

### ISSUE THREAD

**Issue by abinoam** [code-newbies/ruby-monday-blog#79]
There's some branches that are old and others that are already merged.

Could we delete them all?

**Comment by gurgelrenan** [comment]
We could delete all this **merged** branch, right? 

![screen shot 2015-09-01 at 21 47 30](https://cloud.githubusercontent.com/assets/691159/9620652/23e6f8f4-50f3-11e5-90d0-5fd4668ae775.png)

**Comment by abinoam** [comment]
Yes. Otherwise it will accumulate.
@ajose01 Do you authorize?

**Comment by allanbreyes** [comment]
Went on a branch pruning spree
