### ISSUE TITLE
Add responsiveness to site for mobile/desktop

### ISSUE THREAD

**Issue by ajose01** [code-newbies/ruby-monday-blog#8]
so that users can have a good experience regardless of platform.

This may require using a responsive CSS framework. Review some of the most used frameworks, discuss in slack channel, and set-up.

Some options:
Twitter Bootstrap 3
Foundation

**Comment by jaywilburn** [comment]
I can take this - we will go with Bootstrap since I'm sure most will know this.

**Comment by jaywilburn** [comment]
Added Bootstrap and made sure that the pages respond as needed. All done.
