### ISSUE TITLE
Everyone should run `gem update bundler`

### ISSUE THREAD

**Issue by allanbreyes** [code-newbies/ruby-monday-blog#83]
We're getting some conflicts across PRs and merges because different people are using different versions of bundler.  Everyone should run `gem update bundler` prior to running any bundle commands.  You can check your version via:

```
bundle --version
```

You should be on `1.10.6`

**Comment by gurgelrenan** [comment]
Is there any way to force this kind of behavior?

**Comment by abinoam** [comment]
Se PR #87
